spring:
  h2:
    console.enabled: true
    console.settings.trace: false
  datasource:
    url: jdbc:h2:mem:mydb
    #    url: jdbc:h2:file:/data/demo
    username: sa
    #    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect