spring:
  h2:
    console.enabled: true
    console.settings.trace: false
  datasource:
    #url: jdbc:h2:file:./data.db
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    #    url: jdbc:h2:file:/data/demo
    username: sa
    #    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
